'use client';

const SAMPLES = [
  '/samples/sample_deck_startup_1779421719545.png',
  '/samples/sample_deck_business_1779421734567.png',
  '/samples/sample_deck_marketing_1779421748296.png',
  '/samples/sample_deck_minimalist_1779421774126.png',
  '/samples/sample_deck_tech_1779421787828.png',
  '/samples/sample_deck_travel_1779421811640.png',
  '/samples/sample_deck_realestate_1779421828598.png',
  '/samples/sample_deck_app_1779421840344.png',
  '/samples/sample_deck_food_1779421856957.png',
  '/samples/sample_deck_edu_1779421871467.png',
];

export function SampleCarousel() {
  return (
    <div className="w-full relative overflow-hidden py-16 bg-white/40 border-y border-black/[0.04] mt-12 sm:mt-20">
      <style>{`
        @keyframes marquee {
          0% { transform: translateX(0); }
          100% { transform: translateX(-50%); }
        }
        .marquee-track {
          display: flex;
          gap: 1.5rem;
          width: max-content;
          animation: marquee 40s linear infinite;
          will-change: transform;
        }
        @media (min-width: 640px) {
          .marquee-track { gap: 2rem; }
        }
      `}</style>

      <div className="text-center mb-8 px-4">
        <h2 className="text-xl sm:text-2xl font-bold text-slate-800">Beautiful presentations generated by AI</h2>
        <p className="text-sm text-slate-500 mt-2">Explore some of the stunning decks created using Orbstera.</p>
      </div>

      {/* Fade edges */}
      <div className="pointer-events-none absolute left-0 top-0 bottom-0 w-16 sm:w-32 bg-gradient-to-r from-white/90 to-transparent z-10" />
      <div className="pointer-events-none absolute right-0 top-0 bottom-0 w-16 sm:w-32 bg-gradient-to-l from-white/90 to-transparent z-10" />

      {/* Scrolling container — duplicated for seamless loop */}
      <div className="marquee-track">
        {[...SAMPLES, ...SAMPLES].map((src, i) => (
          <div
            key={i}
            className="relative w-[280px] h-[158px] sm:w-[400px] sm:h-[225px] rounded-xl overflow-hidden shadow-[0_8px_30px_rgb(0,0,0,0.12)] border border-black/5 flex-shrink-0 hover:-translate-y-2 transition-transform duration-300"
          >
            <img
              src={src}
              alt={i < SAMPLES.length ? `Generated presentation sample ${i + 1}` : ''}
              className="w-full h-full object-cover"
              loading="lazy"
            />
          </div>
        ))}
      </div>
    </div>
  );
}
