'use client';

import React from 'react';
import { Footer } from '@/components/layout/Footer';

export default function TermsPage() {
  return (
    <main className="min-h-screen w-full bg-white pt-32 pb-16 font-sans text-slate-900">
      <div className="max-w-4xl mx-auto px-6 sm:px-12">
        <h1 className="text-4xl md:text-5xl font-bold mb-8 text-[#1E293B]">Terms of Service</h1>
        <p className="text-sm text-slate-500 mb-12">Last Updated: May 23, 2026</p>

        <div className="prose prose-slate max-w-none text-slate-600 space-y-6">
          <section>
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Orbstera platform, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">2. Description of Service</h2>
            <p>
              Orbstera provides an AI-powered presentation generation and editing platform. The service is provided "as is" and we reserve the right to modify, suspend, or discontinue any part of the service at any time without prior notice.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">3. User Accounts</h2>
            <p>
              You are responsible for safeguarding your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use or security breaches.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">4. Content and AI Generation</h2>
            <p>
              The presentations, text, images, and other materials generated by Orbstera are produced using artificial intelligence based on your prompts. You retain all rights to the prompts you provide. You are granted a commercial license to use the generated output, provided it does not violate any laws or third-party rights.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">5. Credits and Subscriptions</h2>
            <p>
              Usage of the platform requires credits, which are granted based on your subscription tier. Credits do not roll over month-to-month on the Free plan. Paid subscriptions automatically renew unless canceled prior to the billing cycle.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">6. Limitation of Liability</h2>
            <p>
              In no event shall Orbstera be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the platform.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-slate-900 mb-4">7. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which Orbstera operates, without regard to its conflict of law provisions.
            </p>
          </section>
        </div>
      </div>
      <div className="mt-24">
        <Footer />
      </div>
    </main>
  );
}
